import { createServer } from 'http';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { networkInterfaces } from 'os';
import { isIP } from 'net';
import crypto from 'crypto';
import configManager from './config/config-manager.js';
import { DockerHelper } from './utils/docker-helper.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 3000;
const providedSetupAccessToken = String(process.env.SETUP_ACCESS_TOKEN || '').trim();
const setupAccessTokenAutoGenerated = providedSetupAccessToken.length === 0;
const setupAccessToken = setupAccessTokenAutoGenerated
  ? crypto.randomBytes(32).toString('hex')
  : providedSetupAccessToken;
const setupSessionCookieName = 'setup_auth';
const setupSessionCookieValue = crypto.createHash('sha256').update(setupAccessToken).digest('hex');

function normalizeHost(host) {
  let value = String(host || '').trim().toLowerCase();
  if (!value) return '';

  // Host headers can include bracketed IPv6.
  if (value.startsWith('[') && value.endsWith(']')) {
    value = value.slice(1, -1);
  }

  return value;
}

function hostFromHeader(hostHeader) {
  const value = String(hostHeader || '').trim();
  if (!value) return '';

  if (value.startsWith('[')) {
    const end = value.indexOf(']');
    if (end > 1) return normalizeHost(value.slice(1, end));
    return normalizeHost(value);
  }

  const firstColon = value.indexOf(':');
  if (firstColon !== -1 && value.indexOf(':', firstColon + 1) === -1) {
    return normalizeHost(value.slice(0, firstColon));
  }

  return normalizeHost(value);
}

function getAllowedSetupHosts(reqHostHeader) {
  const allowedHosts = new Set(['localhost', '127.0.0.1', '::1', '0.0.0.0']);
  const hostFromReq = hostFromHeader(reqHostHeader);
  if (hostFromReq) allowedHosts.add(hostFromReq);

  const interfaces = networkInterfaces();
  Object.values(interfaces).forEach((iface) => {
    (iface || []).forEach((entry) => {
      const address = normalizeHost(entry?.address);
      if (address) allowedHosts.add(address);
    });
  });

  return allowedHosts;
}

function isAllowedSetupOrigin(origin, reqHostHeader) {
  if (!origin) return true;

  let originUrl;
  try {
    originUrl = new URL(origin);
  } catch {
    return false;
  }

  if (originUrl.protocol !== 'http:' && originUrl.protocol !== 'https:') {
    return false;
  }

  const originHost = normalizeHost(originUrl.hostname);
  if (!originHost) return false;

  // Allow setup access from any direct IP origin (LAN/public).
  if (isIP(originHost)) return true;

  const allowedHosts = getAllowedSetupHosts(reqHostHeader);
  return allowedHosts.has(originHost);
}

function parseCookies(cookieHeader) {
  const parsed = {};
  String(cookieHeader || '')
    .split(';')
    .map((part) => part.trim())
    .filter(Boolean)
    .forEach((part) => {
      const idx = part.indexOf('=');
      if (idx === -1) return;
      const key = part.slice(0, idx).trim();
      const value = part.slice(idx + 1).trim();
      parsed[key] = value;
    });
  return parsed;
}

function hasValidSetupSession(req) {
  const cookies = parseCookies(req.headers.cookie || '');
  return cookies[setupSessionCookieName] === setupSessionCookieValue;
}

// Generate random secrets
function generateSecret(bytes = 64) {
  return crypto.randomBytes(bytes).toString('hex');
}

function generateDefaults() {
  return {
    JWT_SECRET: generateSecret(64),
    PROXY_CHECK_TOKEN: generateSecret(32),
    DB_PASSWORD: generateSecret(32)
  };
}

function readPgSecret() {
  const secretPath = '/run/pg-secret/postgres.secret';
  try {
    const value = readFileSync(secretPath, 'utf-8').trim();
    return value || '';
  } catch {
    return '';
  }
}

// Parse .env.example to get all variables with comments
function parseEnvExample() {
  const examplePath = join(__dirname, '.env.example');
  const content = readFileSync(examplePath, 'utf-8');
  const lines = content.split('\n');

  const sections = [];
  let currentSection = { name: 'General', variables: [] };

  lines.forEach(line => {
    line = line.trim();

    if (!line || line.startsWith('#')) {
      if (line.startsWith('# ') && line.length > 2) {
        // New section
        if (currentSection.variables.length > 0) {
          sections.push(currentSection);
        }
        currentSection = { name: line.substring(2).trim(), variables: [] };
      }
      return;
    }

    const [key, ...valueParts] = line.split('=');
    const value = valueParts.join('=');

    if (key) {
      currentSection.variables.push({ key: key.trim(), value: value || '' });
    }
  });

  if (currentSection.variables.length > 0) {
    sections.push(currentSection);
  }

  return sections;
}

// Write configuration to .env file
function saveEnvFile(config) {
  const envPath = join(__dirname, '.env');
  const sections = parseEnvExample();
  const lines = [];

  sections.forEach(section => {
    lines.push(`# ${section.name}`);
    section.variables.forEach(({ key }) => {
      const value = config[key] !== undefined ? config[key] : '';
      lines.push(`${key}=${value}`);
    });
    lines.push('');
  });

  writeFileSync(envPath, lines.join('\n'), 'utf-8');
  console.log('SUCCESS: Configuration written to .env file');
}

// Read HTML template
function getSetupHTML() {
  const htmlPath = join(__dirname, 'templates', 'setup-wizard.html');
  if (existsSync(htmlPath)) {
    return readFileSync(htmlPath, 'utf-8');
  }
  // Fallback to old setup
  const oldPath = join(__dirname, 'templates', 'setup.html');
  if (existsSync(oldPath)) {
    return readFileSync(oldPath, 'utf-8');
  }
  return '<html><body><h1>Setup page not found</h1></body></html>';
}

// Read JS file
function getSetupJS() {
  const jsPath = join(__dirname, 'setup-wizard.js');
  if (existsSync(jsPath)) {
    return readFileSync(jsPath, 'utf-8');
  }
  return '';
}

// Create HTTP server
const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const origin = String(req.headers.origin || '');
  const requestHostHeader = String(req.headers.host || '');
  const isAllowedOrigin = isAllowedSetupOrigin(origin, requestHostHeader);
  const setupQueryToken = String(url.searchParams.get('token') || '');
  const hasSetupSession = hasValidSetupSession(req);

  // Public health endpoint so Docker can keep the container healthy while setup is pending.
  if (url.pathname === '/health' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' });
    res.end(JSON.stringify({
      status: 'healthy',
      configured: false,
      setupRequired: true,
      mode: 'setup'
    }));
    return;
  }

  if (!isAllowedOrigin) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ success: false, error: 'Cross-origin setup requests are not allowed' }));
    return;
  }

  if (origin && isAllowedOrigin) {
    res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Vary', 'Origin');
  }
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  const requiresSetupSession = url.pathname.startsWith('/api/setup/');
  if (requiresSetupSession && !hasSetupSession) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ success: false, error: 'Setup authorization required' }));
    return;
  }

  // API: Check if setup is complete
  if (url.pathname === '/api/config-status' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      configured: false,
      setupRequired: true,
      setupUrl: '/setup?token=<SETUP_ACCESS_TOKEN>'
    }));
    return;
  }

  // API: Get configuration structure
  if (url.pathname === '/api/setup/config' && req.method === 'GET') {
    const sections = parseEnvExample();
    const defaults = generateDefaults();

    // Load existing config from Redis
    const existingConfig = configManager.getAll();

    // Merge with defaults
    sections.forEach(section => {
      section.variables.forEach(variable => {
        if (existingConfig[variable.key]) {
          variable.value = existingConfig[variable.key];
        } else if (defaults[variable.key]) {
          variable.value = defaults[variable.key];
        }
      });
    });

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ sections, defaults }));
    return;
  }

  // API: Validate configuration
  if (url.pathname === '/api/setup/validate' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', () => {
      try {
        const config = JSON.parse(body);
        delete config.__setupToken;
        const errors = configManager.validateConfig(config);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ valid: errors.length === 0, errors }));
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ valid: false, errors: ['Invalid JSON'] }));
      }
    });
    return;
  }

  // API: Save configuration
  if (url.pathname === '/api/setup/save' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      try {
        const config = JSON.parse(body);
        delete config.__setupToken;
        const errors = configManager.validateConfig(config);

        if (errors.length > 0) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ success: false, errors }));
          return;
        }

        // Save to both Redis and .env file
        await configManager.saveToRedis(config);
        saveEnvFile(config);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true, message: 'Configuration saved successfully!' }));

        // Exit after 2 seconds to allow the response to be sent
        setTimeout(() => {
          console.log('SUCCESS: Configuration saved to Redis & .env. Exiting setup mode...');
          process.exit(0);
        }, 2000);
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, errors: [err.message] }));
      }
    });
    return;
  }

  // API: Import complete configuration (drag & drop)
  if (url.pathname === '/api/setup/import' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      try {
        const config = JSON.parse(body);
        delete config.__setupToken;
        const errors = configManager.validateConfig(config);

        if (errors.length > 0) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ success: false, errors }));
          return;
        }

        // Save to both Redis and .env file
        await configManager.saveToRedis(config);
        saveEnvFile(config);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true, message: 'Configuration imported and saved!' }));

        // Exit after 2 seconds
        setTimeout(() => {
          console.log('SUCCESS: Configuration imported successfully. Exiting setup mode...');
          process.exit(0);
        }, 2000);
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, errors: [err.message] }));
      }
    });
    return;
  }

  // API: Detect Docker
  if (url.pathname === '/api/setup/detect/docker' && req.method === 'GET') {
    try {
      const available = await DockerHelper.isDockerAvailable();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ available }));
    } catch (err) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ available: false, error: err.message }));
    }
    return;
  }

  // API: Test PostgreSQL connection
  if (url.pathname === '/api/setup/test/postgres' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      try {
        const { host, port, database, user, password } = JSON.parse(body);
        const success = await DockerHelper.testPostgresConnection(host, port, database, user, password);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
          success,
          error: success ? null : 'Connection failed'
        }));
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, error: err.message }));
      }
    });
    return;
  }

  // API: Finalize setup (wizard completion)
  if (url.pathname === '/api/setup/finalize' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      try {
        const config = JSON.parse(body);
        delete config.__setupToken;

        // If auto database mode, create PostgreSQL container
        if (config.DB_MODE === 'auto') {
          // In the Compose-based deployment, the PostgreSQL service already exists.
          // Reuse its shared secret instead of spawning a second server with different credentials.
          const composePassword = readPgSecret() || process.env.DB_PASSWORD || '';

          config.DB_HOST = '127.0.0.1';
          config.DB_PORT = '5432';
          config.DB_NAME = 'nebulaproxy';
          config.DB_USER = 'nebulaproxy';
          config.DB_PASSWORD = composePassword;

          if (!composePassword) {
            throw new Error('Unable to load PostgreSQL password from /run/pg-secret/postgres.secret');
          }

          console.log('SUCCESS: PostgreSQL configuration loaded from Compose secret');
        }

        // Remove DB_MODE from final config
        delete config.DB_MODE;

        // Validate final configuration
        const errors = configManager.validateConfig(config);

        if (errors.length > 0) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ success: false, errors }));
          return;
        }

        // Save configuration
        await configManager.saveToRedis(config);
        saveEnvFile(config);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
          success: true,
          message: 'Setup completed successfully!',
          dbCreated: config.DB_MODE === 'auto'
        }));

        // Exit after 2 seconds
        setTimeout(() => {
          console.log('SUCCESS: Setup wizard completed. Starting main application...');
          process.exit(0);
        }, 2000);
      } catch (err) {
        console.error('Setup finalization error:', err);
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, errors: [err.message] }));
      }
    });
    return;
  }

  // Serve setup JavaScript
  if (url.pathname === '/setup-wizard.js' && req.method === 'GET') {
    if (!hasSetupSession) {
      res.writeHead(401, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('Setup authorization required');
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/javascript' });
    res.end(getSetupJS());
    return;
  }

  // Serve setup HTML
  if (url.pathname === '/setup' || url.pathname === '/setup/' || url.pathname === '/' || url.pathname === '/index.html') {
    if (!hasSetupSession) {
      if (setupQueryToken && setupQueryToken === setupAccessToken) {
        res.writeHead(302, {
          Location: '/setup',
          'Set-Cookie': `${setupSessionCookieName}=${setupSessionCookieValue}; Path=/; HttpOnly; SameSite=Strict; Max-Age=900`
        });
        res.end();
        return;
      }
      res.writeHead(401, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('Setup authorization required. Open /setup?token=<SETUP_ACCESS_TOKEN>.');
      return;
    }
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(getSetupHTML());
    return;
  }

  // 404
  res.writeHead(404);
  res.end('Not found');
});

// Start server
async function startSetupServer() {
  try {
    // Initialize config manager
    await configManager.init();

    // Check if setup is needed
    if (configManager.isConfigured()) {
      console.log('SUCCESS: Configuration already complete. Skipping setup mode.');
      process.exit(0);
      return;
    }

    if (!setupAccessTokenAutoGenerated && setupAccessToken.length < 32) {
      throw new Error('SETUP_ACCESS_TOKEN must be at least 32 characters.');
    }

    // Start setup server
    server.listen(PORT, '0.0.0.0', () => {
      console.log('='.repeat(70));
      console.log('  [START] NebulaProxy Setup Required');
      console.log('='.repeat(70));
      console.log('');
      if (setupAccessTokenAutoGenerated) {
        console.log('  WARNING: SETUP_ACCESS_TOKEN not set, generated temporary token for this setup session.');
        console.log(`  📡 Setup wizard: http://your-ip:3001/setup?token=${setupAccessToken}`);
      } else {
        console.log('  Using SETUP_ACCESS_TOKEN from environment.');
        console.log('  📡 Setup wizard: http://your-ip:3001/setup?token=<SETUP_ACCESS_TOKEN>');
      }
      console.log(`  📡 Backend API: http://localhost:${PORT}`);
      console.log('');
      console.log('  Please complete the setup wizard to configure your proxy.');
      console.log('  Once setup is complete, the proxy will start automatically.');
      console.log('');
      console.log('='.repeat(70));
    });
  } catch (error) {
    console.error('ERROR: Failed to start setup server:', error.message);
    console.error('');
    console.error('  Make sure Redis is running and accessible.');
    console.error('  Check your REDIS_HOST and REDIS_PORT environment variables.');
    console.error('');
    process.exit(1);
  }
}

startSetupServer();

